
server:
  port: 9090

spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true

keycloak:
  realm: service
  auth-server-url: http://localhost:8081/auth
  resource: servicecompany
  public-client: true
  bearer-only: true
  enabled: true



